// <auto-generated />
namespace lec0Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Category_AddFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_AddFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201905062110420_Category_AddFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
